{% set name = "fixie" %}
{% set version = "0.0.3" %}
{% set sha256 = "f08e8ada650ad1a78d0a968de96e17ace14116ec303573397e5ea265fc1a84db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - xonsh
    - cerberus
    - tornado

test:
  imports:
    - fixie
    - fixie.environ

about:
  home: http://github.com/ergs/fixie
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cyclus-as-a-Service'

extra:
  recipe-maintainers:
    - scopatz
