travis:
  secure:
    BINSTAR_TOKEN: wL2Y7VfWIkwFW4bIlvg7ubuyRtDllNBk/E9YXTGrOw4ISxVUVQUR59E0/2G1St8OPlE48fI3+w2MMS2RuPQsddlxmOHP8LCgWg/LlJSOdCXb/rw8blPVBnlSdrbcY9uk+4wa/K12RnEtHs0HAYzJ9sw2+cAx5fM9wQc2x/LcaHMAqzbF6SnVKn4i6uzxLgR/nShnDJAUHGdKWTXvXviohCjNqQa/azgnEnLI0sAwJO8ZQ96UN3HRG/M327ozYrEBTf5+4CjjaN7cyoA4OlPzI70YQpWWdSDq6KwQGoxTXn3Oo/eAb808ZDZVNjM7LaNPYkHs25Xe33HffVxSNSVe618feVnOqtS0LVhygEGzXG6dM59OBBvgv4JuEF/NYSZaS3IMC3BUUjtj11wbzhni90A282Ei7F6nuWGofZuvujqTPLYxr9ZZsbHr84hGmkvjnXbrV+mJGggvMUsAqANKL9qzZVuIF+8wHfzPC1DdQDnjQSYmy27wq79xXGdSdw4eiQ091gzylKv7V5BQKq9yOCZcnRmTdIqRhm/AO/wE7HKiE63G1ZX8/hdyuPVeKqPEAGYc72S8yFAiJ4pklhSUX2Z8oLQnyhqaumDKOAyfverZ37XsqtlmeKa3bpe1pgpvGvgJ4VUlORGhjT2uc3q5UIxxmyQxk40rIoofwBJme88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
