travis:
  secure:
    BINSTAR_TOKEN: S4bpovtWm/hiaDBFN14xEypHBSoTQhyoD0x4R/4K9y0qxMmO35sGhxyWUi1SHYLa3n4gHHmj0yHJo52xHw9RqcOiCbSdqe7HDI7uA7/NXuzRxo07uhkmRHVLWq4B6G4d4n/rp4sW9hMkW36HYoziohSvw2LkBUdIW4utXdw/NaC41iDaSGo8QoPYBYgb8G6lJGvSQN05ci2bLb+Xm4yiASqJ/XMu/spOuDm100vtyIbKXJNau/nDLiis06bXKrs4VJxXLi2I5uFQuhVUN0rcGixc8X4KVr2MEqNAjr/PXw16q3wvC4anhVrWCbPxLI+7+xdrdlqUfK6EfeQKRsujTek1MFH7oSpEFE5cXE2H8kj0wSmbRjaHI905IYCGjCW3TAJfx9AzF7sGthTxti4A9TRT7GnwcGsCuxQWE5UULEd0ViDo0WBLzxoB+Syf3+wYxL7p42gqeImH4HX9jmoYaNRt/jdA5UNtJK7smWALBz9P3QZMHxnt5x7YGULi0W04BQfyvJdbHoGO+yMD4s4CiGY3hmjGjBsjr/CkjESmuKykl7E0TAG3SgL2nABb/RzI6GVyTFxUYkJXhDFefJNRHD1TvdBZAiq/sfMSG6G8rx/QEz2CjOx6amlpSDThIo54XmL6z3LUMwE+LHjFTzwJP2xpN2CQXF5KGLr59HlznYo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
